In [1]:
import numpy as np
import matplotlib.pyplot as plt

from eigenvalue_solver import generate_symmetric, compute_eigenvalues_eigenvectors

In [2]:
def compute_angle(v1, v2):
    """Compute the angle between two vectors.
    
    Parameters
    ----------
    v1 : np.ndarray
        The first vector.
    v2 : np.ndarray
        The second vector.
    
    Returns
    -------
    angle : float
        The angle between the two vectors."""
    return np.arccos(v1.T @ v2 / (np.linalg.norm(v1) * np.linalg.norm(v2)))

Now we will generate the symmetric matrix A, that we will compute the eigenvalues of.

In [3]:
N = 6
A = generate_symmetric(N)
print(A)

[[0.49969432 0.20426618 0.1863525  0.4636774  0.68510798 0.18171879]
 [0.20426618 0.48024773 0.40624058 0.27008179 0.55602103 0.28175302]
 [0.1863525  0.40624058 0.10188615 0.496746   0.50538249 0.1579067 ]
 [0.4636774  0.27008179 0.496746   0.06309849 0.51591961 0.51621161]
 [0.68510798 0.55602103 0.50538249 0.51591961 0.97858347 0.34524998]
 [0.18171879 0.28175302 0.1579067  0.51621161 0.34524998 0.04031375]]


We will first use our neural network based approach.

In [4]:
nnval, nnvec = compute_eigenvalues_eigenvectors(A)
print(nnval)
print(nnvec)

Found eigenvector 1 (iteration 1)
Failed to find eigenvector: Cost too high (iteration2)
Found eigenvector 2 (iteration 3)
Found eigenvector 3 (iteration 4)
Failed to find eigenvector: Cost too high (iteration5)
Found eigenvector 4 (iteration 6)
Failed to find eigenvector: Cost too high (iteration7)
Failed to find eigenvector: Cost too high (iteration8)
Found eigenvector 5 (iteration 9)
Failed to find eigenvector: Cost too high (iteration10)
Failed to find eigenvector: Cost too high (iteration11)
Failed to find eigenvector: Cost too high (iteration12)
Failed to find eigenvector: Cost too high (iteration13)
Failed to find eigenvector: Cost too high (iteration14)
Failed to find eigenvector: Cost too high (iteration15)
Found eigenvector 6 (iteration 16)
[ 0.14425201 -0.62729249 -0.12846113  2.46711493 -0.05514846  0.36335905]
[[ 0.03174839  0.20177533  0.22091589  0.39848486  0.5663826   0.65565763]
 [-0.29127822 -0.11690719 -0.04189745  0.36907899  0.57564712 -0.65737305]
 [ 0.12994269  

Next, we compare our results with eigenvalues and eigenvectors computed using the numpy library.

In [5]:
val, vec = np.linalg.eig(A)
for i in range(N):
    if vec[0, i] < 0:
        vec[:, i] = -vec[:, i]

idx = sorted([(vec[0, i], i) for i in range(N)])
idx = [i[1] for i in idx]
val = val[idx]
vec = vec[:, idx]
print(val)
print(vec)

[ 0.14425211 -0.62729381 -0.12846239  2.46712105 -0.05515206  0.36335901]
[[ 0.03202882  0.20193313  0.21881617  0.39898406  0.56666903  0.65575496]
 [-0.29081013 -0.11627481 -0.04368054  0.3700923   0.57505808 -0.65752684]
 [ 0.13011413  0.43995177  0.70151658  0.32459808 -0.33022434 -0.28805419]
 [ 0.55747908 -0.72229493  0.13301748  0.37572404 -0.09294372  0.00252218]
 [-0.4971552  -0.05482421 -0.31327196  0.62320205 -0.48002881  0.18133734]
 [ 0.58269007  0.47689618 -0.58502393  0.2625455   0.0089502  -0.14757736]]


Compute angle between computed eigenvectors and numpy eigenvectors

In [11]:
angles = [compute_angle(nnvec[:, i].reshape(N, 1), vec[:, i].reshape(N, 1))[0,0] for i in range(N)]
print(*angles, sep="\n")
print("mean angle:", np.mean(angles))

0.0007350728035931086
0.0007572995209456287
0.0032415126846173804
0.001533759301925556
0.0035158719997836047
0.0006137225616801615
mean angle: 0.00173287314542424


Compute absolute error between computed eigenvalues and numpy eigenvalues

In [16]:
errors = [abs(nnval[i] - val[i]) for i in range(N)]
print(*errors, sep="\n")
print("mean absolute error:", np.mean(errors))
print("max absolute error:", np.max(errors))
print("min absolute error:", np.min(errors))

1.03355881408973e-07
1.3197551427257537e-06
1.2620045375943967e-06
6.115988085308999e-06
3.5977950763182998e-06
3.978380230806877e-08
mean absolute error: 2.073113754277415e-06
max absolute error: 6.115988085308999e-06
min absolute error: 3.978380230806877e-08


Compute relative error between computed eigenvalues and numpy eigenvalues

In [17]:
rel_errors = [abs(nnval[i] - val[i]) / abs(val[i]) for i in range(N)]
print(*rel_errors, sep="\n")
print("mean relative error:", np.mean(rel_errors))
print("max relative error:", np.max(rel_errors))
print("min relative error:", np.min(rel_errors))

7.164947558738334e-07
2.103886754403669e-06
9.82392191637955e-06
2.4789979770234476e-06
6.52341037353723e-05
1.0948896488692241e-07
mean relative error: 1.3411149017323286e-05
max relative error: 6.52341037353723e-05
min relative error: 1.0948896488692241e-07
